import os


movie_script = {
    "name": "Movie agent",

    "variables": {
        "apikey": os.getenv("REPLICATE_API"),
        "prompt": "Write a story about minecraft",
        "context": "",

        # Agent specific fields
        "title": "",
        "genre": "Science fiction",
        "tone": "tone",
        "logline": "logline",
        "protagonist": "",
        "conflict": "conflict",
        "length": "",

        "format1": "ACT ONE:\nContents here.",
        "format2": "ACT TWO:\nContents here",
        "format3": "ACT THREE:\nContents here",

        # Agent return fields. need not declared, if a previous node writes to a variable that isnt created, a new variable is created at rumtime, 
        # the subsequent node can still reference it.
        "sypnosis": "",
        "characters": "",
        "outline": "",
        "actOne": "",
        "actTwo": "",
        "actThree": ""
    },

    "promptChain": [
        {
            "id": "synopsis",
            "type": "PromptNode",
            "name": "Synopsis",
            "system": "You are a story development expert creating a synopsis for a {genre} film with a {tone} tone.",
            "user": "Write a synopsis for '{title}' based on the logline: {logline}\nSetting: {setting}\nProtagonist: {protagonist}\nMain Conflict: {conflict}",
            "apiKey": "{apikey}",
            "llm": "claude",
            "model": "claude-3-opus-20240229",
            "temperature": 0.7,
            "maxTokens": 4000,
            "output": "synopsis",
        },
        {
            "id": "characters",
            "type": "PromptNode",
            "name": "Character Development",
            "system": "You are a character development specialist for {genre} films.",
            "user": "Develop the main characters for '{title}'.\nInclude:\n- Protagonist: {protagonist}\n- Antagonist\n- Supporting characters\n\nBased on synopsis:\n{synopsis}",
            "apiKey": "{apikey}",
            "llm": "claude",
            "model": "claude-3-opus-20240229",
            "temperature": 0.7,
            "maxTokens": 4000,
            "output": "characters",
        },
        {
            "id": "outline",
            "type": "PromptNode",
            "name": "Scene Outline",
            "system": "You are a screenplay structuralist creating an outline for a {length} {genre} film.",
            "user": "Create a detailed scene-by-scene outline following three-act structure.\nTitle: {title}\nTone: {tone}\n\nBased on:\n{characters}\n\nSynopsis: {synopsis}",
            "apiKey": "{apikey}",
            "llm": "claude",
            "model": "claude-3-opus-20240229",
            "temperature": 0.7,
            "maxTokens": 4000,
            "output": "outline",
        },
        {
            "id": "actOne",
            "type": "PromptNode",
            "name": "Act One",
            "system": "You are a screenwriter writing Act One in {format1} format for a {genre} film.",
            "user": "Write Act One of '{title}' including setup, inciting incident, and first plot point.\nFollow {tone} tone and proper screenplay formatting.\n\nBased on outline:\n{outline}",
            "apiKey": "{apikey}",
            "llm": "claude",
            "model": "claude-3-opus-20240229",
            "temperature": 0.7,
            "maxTokens": 4000,
            "output": "actOne",
        },
        {
            "id": "actTwo",
            "type": "PromptNode",
            "name": "Act Two",
            "system": "You are a screenwriter writing Act Two in {format2} format for a {genre} film.",
            "user": "Write Act Two of '{title}' including rising action, midpoint, and complications.\nMaintain {tone} tone and proper formatting.\n\nBased on Act One:\n{actOne}\n\nOutline: {outline}",
            "apiKey": "{apikey}",
            "llm": "claude",
            "model": "claude-3-opus-20240229",
            "temperature": 0.7,
            "maxTokens": 4000,
            "output": "actTwo",
        },
        {
            "id": "actThree",
            "type": "PromptNode",
            "name": "Act Three",
            "system": "You are a screenwriter writing Act Three for a {genre} film. Format your response as follows:\n{format3}",
            "user": "Write Act Three of '{title}' including climax and resolution.\nMaintain {tone} tone and proper formatting.\n\nPrevious content:\nAct One: [Summarized]\nAct Two: {actTwo}",
            "apiKey": "{apikey}",
            "llm": "claude",
            "model": "claude-3-opus-20240229",
            "temperature": 0.7,
            "maxTokens": 4000,
            "output": "actThree",
        },
        {
            "id": "dialogue",
            "type": "PromptNode",
            "name": "Dialogue Polish",
            "system": "You are a dialogue specialist polishing conversations for {genre} films with {tone} tone.",
            "user": "Review and enhance key dialogue moments throughout the script. Ensure character voices are distinct and consistent. Focus on the most important conversations only.\n\nFull script structure: {fullScript}",
            "apiKey": "{apikey}",
            "llm": "claude",
            "model": "claude-3-opus-20240229",
            "temperature": 0.7,
            "maxTokens": 4000,
            "output": "dialogueRevisions",
        },
        {
            "id": "final-result",
            "type": "ReturnNode",
            "name": "Final Results",
            "output": ["title", "genre", "synopsis", "actOne", "actTwo", "actThree", "dialogueRevisions"]
        }
  ],
}   